### ISSUE TITLE
Removing Mag doesn't work on example gun

### ISSUE THREAD

**Issue by ENVISIONMUSIC** [Tomura/TacticalVRCoreExample#1] opened 2022-04-25 03:10 UTC
While testing the example map with Oculus Touch controllers, I cannot remove the mag that spawns in the gun

**Comment by Tomura** [comment] 2022-04-25 06:59
Can you tell me what exactly you are doing?
The intended behavior for the example gun is the following:
In the case of AR15 style guns, with "Mag Release Near Primary Grip" checked, you need to press the A/X Button on the controller of the primary hand that is gripping the gun. The magazine will unlock and drop free, when it isn't grabbed. When the Magazine is gripped as well, it can be moved by the hand that is gripping the magazine, once it was unlocked.

You should also see the mag release button on the gun's 3D model and the mag catch move a little.
If that does not work, please check in the Character Blueprint whether the Input Action even works at all. For example by placing some debug messages after the corresponding Blueprint nodes.

**Comment by ENVISIONMUSIC** [comment] 2022-04-25 19:26
It looks like the Input Action isn't working at all, after doing some testing and putting debug messages into the action it just doesn't send at all

**Comment by Tomura** [comment] 2022-04-26 09:28
> It looks like the Input Action isn't working at all, after doing some testing and putting debug messages into the action it just doesn't send at all

Ok, so it seems a bit of a deeper problem. I tried it with my RiftS and couldn't reproduce it.
It might be worth to look if the Input Configuration is correct for you in the project settings. 

But I would recommend to make sure that the basics work (Input + Action Binding). Might also be worth trouble shooting in a clean VR template from the Editor. Make sure to also use OpenXR if you want to reproduce the behavior in this project. If the Action Binding does not trigger even with correct Project Settings then it's likely an Engine Issue, Open XR issue or Oculus' openXR integration issue.


If that doesn't help:
I've seen in some of the commits for the VRExpansion Plugin that there recently was some sort of bug with Oculus Controllers, so it might be worth looking into trying other versions of the VR Expansion Plugin. I didn't look much into it because I didn't notice anything with my RiftS. But I actually think this isn't it.

Just delete the VR Expansion Plugin files in this project and replace them with the ones you pulled from it's own git repository. Might be worth trying the newest commit (as the bug should be fixed by now) or maybe some older ones, until you find a version where the bug does not exist.

**Comment by ENVISIONMUSIC** [comment] 2022-04-28 01:16
After testing in other projects as well, it seems to be broken in all projects, not sure what thats about

**Comment by Tomura** [comment] 2022-04-28 07:16
Thanks for the reply. Hope it gets resolved. Dunno if it is a bug in UE4's OpenXR plugin or if it is something on the Oculus side.
I'll close the issue then.

**Closed as completed by Tomura** 2022-04-28 07:16 UTC
Labels: invalid, wontfix
